### PR TITLE
Default to '/' path

### PR DESCRIPTION
**Pull request by JakeRowsell89**
Because everyone seems to set path to '/'  it seems a bit senseless to have path not default to '/'

### CODE REVIEW

**Comment by swagatha-christie** [comment]
By analyzing the blame information on this pull request, we identified @alanclarke, @samuelfullerthomas and @KwanMan to be potential reviewers

**Comment by KidkArolis** [comment]
👍

**Comment by KwanMan** [comment]
Though the majority do this, I have used the current behaviour to set cookies at a specific path, so this is a breaking change

**Comment by roberttod** [comment]
@KwanMan I agree. Would have to increment the major version and then update library by library. Since the lib doesn't change too much anyway, it might be worth doing.

**Pull request closed without merging**
