### PR TITLE
Benchmarks

### PR DESCRIPTION
**Pull request by alanclarke**
Adds benchmarking to cookieman and so far reduces cookie reads from about 0.261ms to about 0.156ms, so about 60% saving.

This is cool because these optimisations don't carry much risk and can be dropped in at any point. Also because cookie reading is expensive and happens a lot in smartserve.js

### CODE REVIEW

**Comment by alanclarke** [comment]
@roberttod @KidkArolis

**Comment by alanclarke** [comment]
added standard so best reviewed commit by commit

**Comment by roberttod** [comment]
Sweeeeet

**Comment by KidkArolis** [comment]
Looks great!

@roberttod @alanclarke Have you seen this browser cookie (in)compatibility table, https://inikulin.github.io/cookie-compat/. Kind of shocking, but I guess not surprising.

Also, how is window.performance.now() different from Date.now()?

**Comment by KidkArolis** [comment]
Ah, it gives you tiny nano seconds or some shit?

**Comment by alanclarke** [comment]
yeah tiny lil nano seconds - 'lil bits' https://www.youtube.com/watch?v=Gj4-E5Hs3Kc

@KidkArolis yeah pretty shocking! A lot of those tests do stupid things that shouldn't happen, but some of them are a bit worrying

**Pull request merged**
